crowds-cure/cancer

- src/shared/SimpleHeaderSection.css
- src/shared/SimpleHeaderSection.js
Create a component to deal with this simple header, so we can use on the other pages.
> Simple Header Component

- src/shared/RankingItem.css
- src/shared/RankingSection.css
- Added missing style in this components
> Ranking Section style changes

- src/shared/StatisticsCard.css
- src/shared/StatisticsSection.css
- src/shared/StatisticsSection.js
- Added missing style in this components
> Statistics Section component

- src/shared/Button.css
- src/shared/Button.js
- src/shared/LogoutSection.js
- Refactor the component
- Added style
> Buttno component

- src/shared/AutoLogoutCountdown.css
- src/shared/AutoLogoutCountdown.js
> Auto Logout Countdown component

- src/App.js
- src/Dashboard.css
- src/GlobalStyles.css
- src/SessionSummary.css
- src/SessionSummary.js
- src/grid-16.css
- src/shared/AutoLogoutCountdown.css
- src/shared/LogoutSection.css
- src/shared/ProgressSection.css
- src/shared/RankingSection.css
- Refactor the session-summary page and introduce a grid-16
- Added CSS to accomplish the page's proposed layout.
> Session summary page

- src/Dashboard.css
- src/Dashboard.js
- src/SessionSummary.css
- src/SessionSummary.js
- src/grid-16.css
- Wrapped the container inner the page div, so the background will remain in the whole page 
- Remove paddings as its not needed anymore
> Adding Layout breakpoints

- src/viewer/Viewer.css
- src/viewer/components/ToolbarButton.css
- Small changes for the tool bar section to make it look better
> Small fixes for Toolbar Section

- src/Dashboard.js
- src/SessionSummary.js
- src/shared/SimpleHeaderSection.css
- src/shared/SimpleHeaderSection.js
- Latest change sin the layout for the header of Dashboard and Session-summary pages
- Restyle for the logout button in the header
> New simple header

- src/case/getNextCase.js
- src/case/getNextCaseForAnnotator.js
- src/shared/getCommunityStats.js
- src/viewer/Viewer.js
Changes from placeholder (random) case selection
to algorithm from design document.
> feat(db): case selection algorithm based on skips

- src/labelling/labelling.js
- src/viewer/CornerstoneViewport.js
- src/viewer/ToolContextMenu.css
- src/viewer/ToolContextMenu.js
- Added button on Right-click menu (Add/Edit Label)
- Added logic to remove labelling component if not used
> feat(labelling): Adding logic to show and hide the labelling component

- src/labelling/labelling.js
- src/select-tree/SelectTree.css
- src/select-tree/SelectTree.js
- src/shared/CaseTypeCard.css
- src/shared/CaseTypeCard.js
- src/shared/LogoutSection.js
- src/viewer/CaseControlButtons.css
- src/viewer/CaseControlButtons.js
- src/viewer/CornerstoneViewport.js
- Fix case control button size
- Fix border of cards on dashboard
- Remove Done button
- Adding feature to save location even if description is not selected 
- Remove right-click component in case of other interactions
> Fix labelling buttons

- package-lock.json
- package.json
- src/TestPage.js
- src/labelling/labelling.js
- src/labelling/labellingData.js
- src/select-tree/SelectTree.css
- src/select-tree/SelectTree.js
- Dynamic header in the search
- Alphabetically order into select-tree itens
> Fix docs issues

- package-lock.json
- package.json
- src/labelling/labelling.css
- src/labelling/labelling.js
- src/select-tree/SelectTree.js
- src/shared/Logo.css
- Added a react npm package to perform transition animations 
- Adding transition to the labelling (fade in and fade out animation)
- Fix small issue on header, misplaced logout.
- Fix small issue on labelling breadcrumb, should add <div.col> only if breadcrumb is present
- Added positioning fix in case if get out of the viewport bounds.
> Fix docs issues (part2)

- src/shared/Modal.css
- Make the modal responsive. If it gets too big (height > viewport) it become scrollable. 
- Set max width to 800px, but it can be change if necessary.
> fix(instruction-modal): Make it responsive

- src/shared/Modal.css
- src/viewer/CaseControlButtons.js
- src/viewer/HeaderSection.js
- src/viewer/MeasurementControl.css
- src/viewer/Viewer.css
- src/viewer/components/ToolbarButton.js
- src/viewer/components/ToolbarSection.css
- src/viewer/components/ToolbarSection.js
- Toolbar is now responsive and supporting mobile
- Measurement control is already being positioned in the mobile layout
NOTE: CaseControl buttons are being removed for now on mobile cause it gonna be positioned in another place.
> Toolbar responsive

- src/viewer/CaseFeedback.js
- Adding 'Didn't measure everything'
- Replacing 'No feedback' with 'None, just want to skip'
> fix(caseFeedback): Update list of case feedback options

- src/labelling/labelling.js
- src/labelling/labellingData.js
- Change to one level labelling 
- Adding touch support on closing the modal with 2s of timeout
> feat(labelling):  

- package-lock.json
- package.json
- src/viewer/CornerstoneViewport.js
- Update cornerstoneTools vNext latest version.
- Reverted workaround
- Added support for multiple button mask on zoom/pan as these should always be active on right/middle buttons.
> Fix multiple button mask

- package-lock.json
- package.json
- Bump version of cornerstoneTools
- Fix viewer loading cases issue related with stackPrefetch
> fix(viewer): Fix viewer issue on loading cases

- public/index.html
- src/App.css
- src/shared/ActivityProgressSection.css
- src/shared/AutoLogoutCountdown.js
- src/shared/CaseTypeCard.css
- src/shared/CaseTypeSection.css
- src/shared/ProgressSection.css
- src/shared/RankingItem.css
- src/shared/RankingSection.css
- src/shared/SimpleHeaderSection.css
- src/shared/StatisticsCard.css
- src/shared/StatisticsSection.css
- yarn.lock
Changes:
- Small css fixes to add Work Sans font
- Lots of small type details
- Small spacing details
> Typographic details

- src/shared/CaseTypeCard.css
- src/shared/CaseTypeSection.css
**Changes:**
- Border now highlights image only
- Text styles change color on hover
- Added some minor easing on image hover
> :balloon: Dashboard case type card hover styles

- public/index.html
- src/shared/Checkbox.css
- src/viewer/CaseFeedback.css
**Changes:**
- Added Roboto font for clearer text at small sizes
- Reduced size between lines
- Reduced space to bottom buttons
> Updated case feedback dialogue to reduce height

- src/Dashboard.js
- src/shared/RankingSection.css
- src/shared/RankingSection.js
- Adding viewAll button and route to leaderboard page
> ViewAll on Top individuals rank

- src/labelling/labelling.js
-  Make labelling checkmark action faster. (it should close the component)
> Labelling: Checkmark close faster

- src/shared/ErrorHandling.js
- src/shared/ProgressSection.js
- Fix for 0 current points showing --- on session summary page
> sessionSummary: 0 points animation issue

- package-lock.json
- package.json
- src/ScreenshotQA.css
- src/ScreenshotQA.js
- Add pagination
- Add user selection
NOTE: Sometimes we get blank pages, its because there is an entry in the measurement table but there is no measurement, we could show the data for this non-measurement item, basically just adding skip: true in the getMeasurements query.
> Feat screenshot pagination

- src/App.js
- src/LogoutTimeoutService.js
- Created a service to control logout on timeout.
- Service configuration is into its own scope but we can/should move it to a shared config place (later)(timeout value and any route to skip)
- If user on leaderboard page will not be redirected
Force Logout after 10 mins
> Logout automatically on timeout (skip for some cases)

- src/shared/SimpleHeaderSection.css
- src/shared/SimpleHeaderSection.js
Added privacy link to the dashboard page;
Changed the links, logo and username positioning across all the devices.
> Adding Privacy link to the dashboard

- src/Dashboard.js
- src/SessionSummary.js
- src/achievements.js
- src/badges.js
- src/notifications/Notification.js
- src/notifications/NotificationContainer.css
- src/notifications/NotificationManager.js
- src/notifications/NotificationService.js
- src/notifications/NotificationToast.css
- src/notifications/NotificationToast.js
- src/shared/AchievementSection.js
- src/shared/determineAchievementsForUser.js
- src/viewer/Viewer.js
- src/viewer/lib/saveAchievementsToDatabase.js
Implemented box and toast notifications for rank badges;
Renamed notification type from `POPUP` to `TOAST`;
> Implementing box and toast notifications for rank badges

- src/SessionSummary.js
- src/caseNotifications.js
- src/notifications/NotificationService.js
- src/viewer/Viewer.js
Added informative notifications to case level;
Fixed issue with session summary page;
> Notifications case

- src/GlobalStyles.css
- src/shared/InstructionsModal.js
- src/shared/SimpleHeaderSection.css
- src/shared/SimpleHeaderSection.js
- src/viewer/CaseFeedback.js
- src/viewer/CaseProgress.js
Added Help link to Dashboard in order to display instructions;
Adjusted the layout across all device types to ensure the new change will not break anything;
> Adding Help link to Dashboard in order to display instructions

- src/ConnectedViewer.js
- src/viewer/CaseControlButtons.css
- src/viewer/CaseFeedback.css
- src/viewer/CaseProgress.css
- src/viewer/CaseProgress.js
- src/viewer/Viewer.js
Added current rank and score to viewer for desktop devices;
> Adding current rank and score to viewer for desktop devices

- src/viewer/CornerstoneViewport.js
- src/viewer/Viewer.js
- src/viewer/lib/getUsername.js
Preventing jump-to-lesion after deleting a measurement;
Credits to @ladeirarodolfo;
> Preventing jump-to-lesion after deleting a measurement

- src/labelling/labelling.js
- src/viewer/Viewer.js
Making labelling popup fade out after 3s;
Credits to @ladeirarodolfo;
> Label modal to fadeout in 3s

- src/viewer/CornerstoneViewport.js
- Force to focus only if  lesion has changed.
- This fixes issues on zooming
> Shall not focus on zooming

- src/viewer/lib/saveMeasurementToDatabase.js
Added team name to measurement object;
> Adding team name to measurement object

- src/viewer/lib/sendSessionStatisticsToDatabase.js
Added `sessionId` attribute to the database's session document structure
> Adding sessionId to the database's session document structure

- src/App.js
- src/Leaderboard.css
- src/Leaderboard.js
- src/LeaderboardFit.css
- src/shared/LeaderboardItem.css
Created a `/leaderboard-fit` route to be used on booth;
Added CSS rules for mobile devices to make it responsive;
> Leaderboard improvements

- src/notifications/NotificationService.js
Fixed issue with first notification not being displayed;
> Fixing issue with first notification not being displayed

- src/shared/LeaderboardItem.js
Omitted notApplicable team from leaderboard;
> Hiding notApplicable team from leaderboard
